SET C51INC=D:\Keil_v5\C51\Inc;D:\Keil_v5\C51\Inc\Atmel
SET C51LIB=D:\Keil_v5\C51\Lib
SET CPU_TYPE=AT89C51
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"D:\Keil_v5\C51\BIN\A51.EXE" @.\Objects\STARTUP._ia
"D:\Keil_v5\C51\BIN\C51.EXE" @.\Objects\main.__i
"D:\Keil_v5\C51\BIN\C51.EXE" @.\Objects\1602.__i
"D:\Keil_v5\C51\BIN\BL51.EXE" @.\Objects\home_tem.lnp
"D:\Keil_v5\C51\BIN\OH51.EXE" ".\Objects\home_tem" 
